### PR TITLE
AcceptPattern

### PR DESCRIPTION
**Pull request by will**

### CODE REVIEW

**Comment by will** [comment]
tested this in real life as well, and it works! Was collecting everything, added the config var, and it started filtering

**Comment by will** [comment]
compiled all regexes in advance for a huge\* performance boost

*did not benchmark at all, @kr said it'd be a good idea

**Comment by kr** [comment]
Heh. I said it'd be cleaner code this way. Avoiding compiling the regexp every time is also nice.

**Comment by will** [comment]
I'm closing this

**Pull request closed without merging**
